development:
  adapter: mysql2 
  encoding: utf8
  reconnect: false
  database: FM
  pool: 5
  username: root
  password: 123456
  host: localhost

test:
  adapter: mysql2 
  encoding: utf8
  reconnect: false
  database: FM1
  pool: 5
  username: root
  password: 123456
  host: localhost

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
